/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppLoader {}
  interface AppLoaderAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppX {
    'instanceID': string;
    'match': MatchResults;
  }
  interface AppXAttributes extends StencilHTMLAttributes {
    'instanceID'?: string;
    'match'?: MatchResults;
  }

  interface AppY {
    'instanceID': string;
    'match': MatchResults;
  }
  interface AppYAttributes extends StencilHTMLAttributes {
    'instanceID'?: string;
    'match'?: MatchResults;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppLoader': Components.AppLoader;
    'AppProfile': Components.AppProfile;
    'AppX': Components.AppX;
    'AppY': Components.AppY;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-loader': Components.AppLoaderAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-x': Components.AppXAttributes;
    'app-y': Components.AppYAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppLoaderElement extends Components.AppLoader, HTMLStencilElement {}
  var HTMLAppLoaderElement: {
    prototype: HTMLAppLoaderElement;
    new (): HTMLAppLoaderElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppXElement extends Components.AppX, HTMLStencilElement {}
  var HTMLAppXElement: {
    prototype: HTMLAppXElement;
    new (): HTMLAppXElement;
  };

  interface HTMLAppYElement extends Components.AppY, HTMLStencilElement {}
  var HTMLAppYElement: {
    prototype: HTMLAppYElement;
    new (): HTMLAppYElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-loader': HTMLAppLoaderElement
    'app-profile': HTMLAppProfileElement
    'app-x': HTMLAppXElement
    'app-y': HTMLAppYElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-loader': HTMLAppLoaderElement;
    'app-profile': HTMLAppProfileElement;
    'app-x': HTMLAppXElement;
    'app-y': HTMLAppYElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
